// Generated by https://quicktype.io

export interface PokemonsResponse {
    count: number;
    next: string;
    previous: null;
    results: Pokemon[];
}

interface Pokemon {
    id: string
    name: string;
    url: string;
}


export interface SimplePokemon {
    id: string
    name: string;
}
